application: lunkaku
version: 1
runtime: python
api_version: 1

handlers:
- url: /s
  static_dir: static
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /admin/.*
  script: main.py
  login: admin
- url: .*
  script: main.py
